### PR TITLE
Fix earpiece app examples

### PR DESCRIPTION
**Pull request by chipaudette**
I modernized the earpiece examples:

* Renamed or replaced a bunch of examples
* Use BLE with the App
* Use better channel names to handle the out-of-order channels
* To use the new SD and LED servicing that's built into the SD writer and Tympan class
* To use the Earpiece Mixer in some examples
* To deprecate the non-working giant example (WDRC_XBand)...though we might resurrect it later

@eyuan-creare , Have you already pointed folks to the Earpiece examples?  Take a look at the new examples...I think that *all* of them have had their name changed.  Does this mess up your interactions with the ASA folks?  Do you want anything changed?

@hgeithner-creare Because of the update to the new SD and LED servicing routines, I actually touched many examples. 
 Please test the sketches below:

* In 02-Utility: Compile SDWriting-01 for RevE.  Start recording, confirm LEDs blink different rates.  Talk into the mics.  Pop out the SD card, and check the audio on your PC to ensure that you got audio.

* In 02-Utility: Compile SDWriting-02 for RevE.  Connect with App.  Start recording.  Confirm LEDs blink different rates.  If the audio worked in the first example, you don't need to check the audio anymore.

* In 05-FullSystems: Compile WDRC_8BandFIR_full for RevE.  Confirm that the App works.  If it has SD writing, confirm that the lights blink at different rate when recording.  If it has App, confirm that the App connects and that it does something.

* In 08-AICShield: Comple SerialControlledSDWriter_Quad.  Start recording.  Confirm LEDs blink different rates.

* In 09-Earpieces: Test all three examples.  Confirm that they compile (RevE), that the earpiece mics work and that the earpiece speaker works.  Check both Left and Right for all three examples.  If it has SD writing, confirm that the lights blink at different rate when recording.  If it has App, confirm that the App connects and that it does something.

### CODE REVIEW

**Comment by chipaudette** [comment]
I'm going to merge this now because I need these changes in other branches.  I'm still hoping that Haley can do the testing, though.

**Comment by eyuan-creare** [comment]
@chipaudette Thanks for reworking these! I only had a bit of time for review, but I appreciated the way that you consolidated servicing routines.  Seems like it will make the core function stand out more clearly.

**Comment by chipaudette** [comment]
@eyuan-creare ,  the main question for you is whether you were OK with changing the names of the examples.  

image

I don't know what you're communicating with the ASA folks and I don't want to undermine your efforts....and the renaming of example programs could be exactly the kind of thing that undermines your efforts.  

Are you Ok with the Earpiece examples being renamed?

**Comment by eyuan-creare** [comment]
> Are you Ok with the Earpiece examples being renamed?
@chipaudette Yes, renaming the earpiece examples is fine.  I'm waiting for the hardware to arrive.

**Comment by hgeithner-creare** [comment]
- _In 02-Utility: Compile SDWriting-01 for RevE. Start recording, confirm LEDs blink different rates. Talk into the mics. Pop out the SD card, and check the audio on your PC to ensure that you got audio._ **Verified all**

- _In 02-Utility: Compile SDWriting-02 for RevE. Connect with App. Start recording. Confirm LEDs blink different rates. If the audio worked in the first example, you don't need to check the audio anymore._  **Verified except the file had no audio. Received the following warning while recording: SD Write Warning: there was a hiccup in the writing. 0.19**

- _In 05-FullSystems: Compile WDRC_8BandFIR_full for RevE. Confirm that the App works. If it has SD writing, confirm that the lights blink at different rate when recording. If it has App, confirm that the App connects and that it does something._ **Verified all. Couldn't connect to App on the first try - recompiled and reconnected successfully on the second try.**

- _In 08-AICShield: Compile SerialControlledSDWriter_Quad. Start recording. Confirm LEDs blink different rates._ **Verified all. Recorded audio was super quiet. No App.**

- _In 09-Earpieces: Test all three examples. Confirm that they compile (RevE), that the earpiece mics work and that the earpiece speaker works. Check both Left and Right for all three examples. If it has SD writing, confirm that the lights blink at different rate when recording. If it has App, confirm that the App connects and that it does something._ @chipaudette this is my first time using the earpieces and I'm not familiar with their behavior. When you have a minute, can you stop by my office to see if what I observed below is a bug or not?
1. AudioPassThru_wEarpieces: **Earpiece only worked with the Left channel. No SD, no App.**
2. EarpieceManualMixing_wSD: **Comments for Enable/Disable in the help menu are flipped. I don't think either channel worked. File had no audio. No App.**
3. TrebleBoost_wComp_wEarpieces_wApp: **I don't think either channel worked. App looks good. Audio file sounds good. Received the following warning while recording: SD Write Warning: there was a hiccup in the writing. 0.38.**

**Pull request merged**
